import sys as _sys
from importlib import import_module as _import_module

from puripuly_heart.app import services as _parent

for _short in (
    "local_asr_cpu_repair",
    "local_asr_diagnostics",
    "local_asr_gpu_provisioning",
    "local_asr_readiness",
    "local_asr_selection",
):
    _module = _import_module(f".{_short}", __name__)
    _sys.modules[f"puripuly_heart.app.services.{_short}"] = _module
    setattr(_parent, _short, _module)
del _module, _short

from .local_asr_cpu_repair import (
    LocalASRCpuModelIdsForProvider,
    LocalASRCpuPeerResume,
    LocalASRCpuProvisioningProvider,
    LocalASRCpuRepairChannel,
    LocalASRCpuRepairEffect,
    LocalASRCpuRepairEffectSink,
    LocalASRCpuRepairEffectType,
    LocalASRCpuRepairOwner,
    LocalASRCpuRepairRequest,
    LocalASRCpuRepairRuntimeState,
    LocalASRCpuRepairRuntimeStateProvider,
    LocalASRCpuRepairSnapshot,
    LocalASRCpuSelfProviderRebuild,
    LocalASRCpuSelfResume,
    LocalASRCpuStatusForProvider,
)
from .local_asr_diagnostics import (
    LocalASRBasicLogSink,
    LocalASRDetailedLogSink,
    LocalASRDiagnosticsGpuEffect,
    LocalASRDiagnosticsGpuEffectSink,
    LocalASRDiagnosticsOwner,
    LocalASRGpuDiscoveryOriginProvider,
)
from .local_asr_gpu_provisioning import (
    LocalASRGpuActivationRetry,
    LocalASRGpuProvisioningDiagnostic,
    LocalASRGpuProvisioningDiagnosticSink,
    LocalASRGpuProvisioningEffect,
    LocalASRGpuProvisioningEffectSink,
    LocalASRGpuProvisioningOwner,
    LocalASRGpuProvisioningState,
    LocalASRGpuProvisioningStateProvider,
    LocalASRGpuProvisioningUiState,
    LocalASRProvisioningProvider,
)
from .local_asr_readiness import (
    LocalASRReadinessAsyncEffect,
    LocalASRReadinessChannel,
    LocalASRReadinessChannelProvider,
    LocalASRReadinessEffect,
    LocalASRReadinessEffectSink,
    LocalASRReadinessEffectType,
    LocalASRReadinessFallback,
    LocalASRReadinessGpuPendingSink,
    LocalASRReadinessGpuStateProvider,
    LocalASRReadinessGpuValidator,
    LocalASRReadinessLoadLogSink,
    LocalASRReadinessOwner,
    LocalASRReadinessProviderAvailable,
    LocalASRReadinessProvisioningProvider,
    LocalASRReadinessState,
    LocalASRReadinessStateProvider,
)
from .local_asr_selection import (
    LOCAL_CPU_AUTO_PROVIDER,
    LOCAL_CPU_DIRECT_MODEL_BY_PROVIDER,
    LOCAL_CPU_PROVIDERS,
    LOCAL_QWEN_PROVIDER,
    LocalASRSelectionDecision,
    local_asr_status_for_provider,
    required_local_asr_model_ids,
    resolve_local_asr_selection,
)

__all__ = [
    "LOCAL_CPU_AUTO_PROVIDER",
    "LOCAL_CPU_DIRECT_MODEL_BY_PROVIDER",
    "LOCAL_CPU_PROVIDERS",
    "LOCAL_QWEN_PROVIDER",
    "LocalASRBasicLogSink",
    "LocalASRCpuModelIdsForProvider",
    "LocalASRCpuPeerResume",
    "LocalASRCpuProvisioningProvider",
    "LocalASRCpuRepairChannel",
    "LocalASRCpuRepairEffect",
    "LocalASRCpuRepairEffectSink",
    "LocalASRCpuRepairEffectType",
    "LocalASRCpuRepairOwner",
    "LocalASRCpuRepairRequest",
    "LocalASRCpuRepairRuntimeState",
    "LocalASRCpuRepairRuntimeStateProvider",
    "LocalASRCpuRepairSnapshot",
    "LocalASRCpuSelfProviderRebuild",
    "LocalASRCpuSelfResume",
    "LocalASRCpuStatusForProvider",
    "LocalASRDetailedLogSink",
    "LocalASRDiagnosticsGpuEffect",
    "LocalASRDiagnosticsGpuEffectSink",
    "LocalASRDiagnosticsOwner",
    "LocalASRGpuActivationRetry",
    "LocalASRGpuDiscoveryOriginProvider",
    "LocalASRGpuProvisioningDiagnostic",
    "LocalASRGpuProvisioningDiagnosticSink",
    "LocalASRGpuProvisioningEffect",
    "LocalASRGpuProvisioningEffectSink",
    "LocalASRGpuProvisioningOwner",
    "LocalASRGpuProvisioningState",
    "LocalASRGpuProvisioningStateProvider",
    "LocalASRGpuProvisioningUiState",
    "LocalASRProvisioningProvider",
    "LocalASRReadinessAsyncEffect",
    "LocalASRReadinessChannel",
    "LocalASRReadinessChannelProvider",
    "LocalASRReadinessEffect",
    "LocalASRReadinessEffectSink",
    "LocalASRReadinessEffectType",
    "LocalASRReadinessFallback",
    "LocalASRReadinessGpuPendingSink",
    "LocalASRReadinessGpuStateProvider",
    "LocalASRReadinessGpuValidator",
    "LocalASRReadinessLoadLogSink",
    "LocalASRReadinessOwner",
    "LocalASRReadinessProviderAvailable",
    "LocalASRReadinessProvisioningProvider",
    "LocalASRReadinessState",
    "LocalASRReadinessStateProvider",
    "LocalASRSelectionDecision",
    "local_asr_cpu_repair",
    "local_asr_diagnostics",
    "local_asr_gpu_provisioning",
    "local_asr_readiness",
    "local_asr_selection",
    "local_asr_status_for_provider",
    "required_local_asr_model_ids",
    "resolve_local_asr_selection",
]
