from importlib import import_module as _import_module

_SUBMODULES = frozenset(
    {
        "root",
        "wiring_application_runtime_logging",
        "wiring_capture_runtime",
        "wiring_composition",
        "wiring_llm_factory",
        "wiring_local_asr_application",
        "wiring_local_asr_provider_runtime",
        "wiring_managed_account",
        "wiring_managed_auth_factory",
        "wiring_microphone_test",
        "wiring_overlay_factory",
        "wiring_peer_application",
        "wiring_provider_runtime",
        "wiring_provider_runtime_policy",
        "wiring_runtime_composition",
        "wiring_runtime_pipeline",
        "wiring_secrets_factory",
        "wiring_stt_factory",
        "wiring_translation_runtime_configuration",
        "wiring_vrc_mic_sync",
    }
)
_EXPORT_SOURCES = {
    "_base_llm_provider_from_resolved_config": "root",
    "_cerebras_api_key_for_resolved_credential": "root",
    "_LazyFactoryLLMProvider": "root",
    "_llm_factory": "root",
    "_openrouter_provider_from_resolved_config": "root",
    "_openrouter_provider_from_resolved_fields": "root",
    "_qwen_api_key_for_resolved_credential": "root",
    "_WIRING_SECRET_KEYS_FOR_COMPATIBILITY_GUARD": "root",
    "annotations": "root",
    "apply_discord_issue_result_to_managed_state": "root",
    "build_custom_vocabulary_runtime_config": "root",
    "build_llm_provider_signature": "wiring_provider_runtime_policy",
    "build_local_asr_session_options": "root",
    "build_managed_identity_state_port": "root",
    "build_openrouter_credential_runtime_config": "root",
    "build_openrouter_release_runtime_config": "root",
    "build_peer_capture_session_config": "root",
    "build_peer_capture_session_config_from_vnext": "root",
    "build_peer_stt_provider_request": "root",
    "build_peer_stt_provider_signature": "root",
    "build_peer_stt_provider_signature_from_vnext": "root",
    "build_peer_stt_runtime_signature": "root",
    "build_peer_stt_runtime_signature_from_vnext": "root",
    "build_self_capture_session_config": "root",
    "build_self_capture_session_config_from_vnext": "root",
    "build_self_capture_vad_signature": "root",
    "build_self_local_asr_transition_request": "root",
    "build_self_stt_provider_request": "root",
    "build_self_stt_provider_request_from_vnext": "root",
    "build_self_stt_provider_signature": "root",
    "build_self_stt_runtime_signature": "root",
    "build_self_stt_runtime_signature_from_vnext": "root",
    "build_translation_runtime_config": "wiring_translation_runtime_configuration",
    "Callable": "root",
    "CaptureDiagnosticsAdapter": "wiring_capture_runtime",
    "CaptureOwnerFactory": "wiring_capture_runtime",
    "compose_application_runtime_logging": "wiring_application_runtime_logging",
    "compose_local_asr_application": "wiring_local_asr_application",
    "compose_managed_account": "wiring_managed_account",
    "compose_peer_application": "wiring_peer_application",
    "compose_peer_capture_session_owner": "root",
    "compose_provider_runtime": "wiring_provider_runtime",
    "compose_runtime_pipeline": "wiring_runtime_pipeline",
    "compose_self_capture_session_owner": "root",
    "compose_vrc_mic_sync": "wiring_vrc_mic_sync",
    "create_desktop_overlay_policy": "wiring_composition",
    "create_gpu_provider_recovery_application_owner": "wiring_composition",
    "create_gpu_runtime_interaction_owner": "wiring_composition",
    "create_llm_provider": "root",
    "create_llm_provider_from_resolved_config": "root",
    "create_local_asr_cpu_repair_owner": "wiring_composition",
    "create_local_asr_diagnostics_owner": "wiring_composition",
    "create_local_asr_provisioning_owner": "root",
    "create_local_asr_readiness_owner": "wiring_composition",
    "create_manual_typing_owner": "wiring_composition",
    "create_microphone_test_capture_adapter": "root",
    "create_peer_capture_admission_adapter": "root",
    "create_peer_capture_audio_loop_adapter": "root",
    "create_peer_capture_source_adapter": "root",
    "create_peer_capture_target_resolver_adapter": "root",
    "create_peer_capture_vad_adapter": "root",
    "create_peer_capture_vad_sink_adapter": "root",
    "create_peer_stt_backend_from_resolved_config": "root",
    "create_provider_credential_verification_interaction_owner": "wiring_composition",
    "create_provider_verifier": "root",
    "create_secret_store": "root",
    "create_self_capture_admission_adapter": "root",
    "create_self_capture_audio_loop_adapter": "root",
    "create_self_capture_source_adapter": "root",
    "create_self_capture_vad_adapter": "root",
    "create_self_capture_vad_sink_adapter": "root",
    "create_stt_backend_from_resolved_config": "root",
    "create_sync_secret_store_adapter": "root",
    "create_vrchat_osc_presence_probe_owner": "wiring_composition",
    "create_windows_desktop_work_area": "wiring_composition",
    "DiagnosticsEnabled": "wiring_local_asr_provider_runtime",
    "DISCORD_AUTH_ERROR_KEY_BY_SUBCODE": "wiring_managed_auth_factory",
    "DiscordManagedBrokerClientAdapter": "root",
    "DiscordOAuthAuthAdapter": "root",
    "DiscordOAuthCallbackRunner": "wiring_managed_auth_factory",
    "DiscordOAuthListenerFactory": "wiring_managed_auth_factory",
    "FaultProfileProvider": "wiring_local_asr_provider_runtime",
    "FinalTranscriptSuppressedSink": "wiring_local_asr_provider_runtime",
    "FIXED_TRANSLATION_POLICY": "root",
    "HardwareFingerprintProvider": "wiring_managed_auth_factory",
    "HuggingFaceXetDownloadAdapter": "root",
    "load_managed_openrouter_user_identifier": "root",
    "LocalASRApplicationRuntime": "wiring_local_asr_application",
    "LocalASRChannel": "wiring_local_asr_application",
    "LocalASRProviderRuntimeFactory": "root",
    "LocalASRProviderRuntimePort": "root",
    "LocalASRProvisioningOwner": "root",
    "logger": "wiring_managed_account",
    "MANAGED_OPENROUTER_RELEASE_SERVICE_REQUIRED_ERROR": "root",
    "ManagedAccountComponents": "wiring_managed_account",
    "ManagedAuthIngressProvider": "wiring_managed_auth_factory",
    "ManagedAuthPersistenceCallbackFactory": "wiring_managed_auth_factory",
    "ManagedAuthReleaseServiceProvider": "wiring_managed_auth_factory",
    "ManagedAuthRuntimeAdapter": "wiring_managed_auth_factory",
    "ManagedAuthRuntimePresenceProvider": "wiring_managed_auth_factory",
    "ManagedAuthSecretStoreFactory": "wiring_managed_auth_factory",
    "ManagedAuthSettingsOwnerComplete": "wiring_managed_auth_factory",
    "ManagedAuthSettingsProvider": "wiring_managed_auth_factory",
    "ManagedAuthSettingsRepositoryFactory": "wiring_managed_auth_factory",
    "ManagedAuthSettingsSink": "wiring_managed_auth_factory",
    "ManagedIdentityPreflightAdapter": "root",
    "ManagedIdentityStateAdapter": "root",
    "ManagedLlmRuntimePort": "wiring_managed_account",
    "ManagedOpenRouterReleaseRuntime": "wiring_managed_account",
    "ManagedSTTProviderFactory": "root",
    "ManagedTranslationContextPort": "wiring_managed_account",
    "ManagedTranslationFounderDialog": "wiring_managed_auth_factory",
    "ManagedTranslationIngressProvider": "wiring_managed_auth_factory",
    "ManagedTranslationPersistSettings": "wiring_managed_auth_factory",
    "ManagedTranslationReleaseServiceProvider": "wiring_managed_auth_factory",
    "ManagedTranslationRuntimeAccess": "wiring_managed_account",
    "ManagedTranslationRuntimeAdapter": "wiring_managed_auth_factory",
    "ManagedTranslationRuntimeSnapshotProvider": "wiring_managed_auth_factory",
    "ManagedTranslationSettingsProvider": "wiring_managed_auth_factory",
    "ManagedUsageRuntimeAdapter": "wiring_managed_account",
    "MicrophoneTestRuntime": "wiring_microphone_test",
    "Path": "root",
    "peer_stt_runtime_intent_from_vnext": "wiring_stt_factory",
    "PeerApplicationRuntime": "wiring_peer_application",
    "PeerCaptureAdmissionPort": "root",
    "PeerCaptureProviderAdapter": "root",
    "PeerCaptureSessionOwner": "root",
    "PeerCaptureTargetResolverPort": "root",
    "project_translation_runtime_settings": "wiring_provider_runtime",
    "project_translation_runtime_settings_from_vnext": "wiring_provider_runtime",
    "provider_runtime_requires_gpu_restart": "wiring_provider_runtime_policy",
    "ProviderChannelResetPort": "root",
    "ProviderRuntimeComponents": "wiring_provider_runtime",
    "ProviderRuntimeEffects": "wiring_provider_runtime",
    "ProviderRuntimeSignatures": "wiring_provider_runtime",
    "ProvisioningDiagnosticSink": "root",
    "ProvisioningStateChanged": "root",
    "replace_translation_runtime_effective_flags": "wiring_translation_runtime_configuration",
    "replace_translation_runtime_enabled": "wiring_translation_runtime_configuration",
    "replace_translation_runtime_settings": "wiring_translation_runtime_configuration",
    "require_secret": "root",
    "require_secret_any": "root",
    "resolve_llm_config": "root",
    "overlay_runtime_intent_from_vnext": "root",
    "resolve_overlay_config": "root",
    "resolve_overlay_config_from_vnext": "root",
    "resolve_peer_stt_config": "root",
    "resolve_peer_stt_runtime_config": "root",
    "resolve_peer_stt_runtime_config_from_vnext": "root",
    "resolve_self_stt_runtime_config": "root",
    "ResolvedPeerSTTConfig": "root",
    "RuntimeCompositionComponents": "wiring_runtime_composition",
    "RuntimePipelineChannelResetRouter": "wiring_runtime_pipeline",
    "RuntimePipelineComponents": "wiring_runtime_pipeline",
    "RuntimePipelineHandle": "wiring_runtime_pipeline",
    "runtime_pipeline_inputs_from_vnext": "wiring_runtime_pipeline",
    "RuntimePipelineLauncher": "wiring_runtime_pipeline",
    "RuntimePipelineResourceOwner": "wiring_runtime_pipeline",
    "SECRETS_PASSPHRASE_ENV": "root",
    "SecretStorePort": "root",
    "SelfCaptureAdmissionPort": "root",
    "SelfCaptureAudioLoop": "root",
    "SelfCaptureDiagnosticSink": "root",
    "SelfCaptureProviderAdapter": "root",
    "SelfCaptureProviderRequestFactory": "root",
    "SelfCaptureSessionOwner": "root",
    "SelfCaptureSourceFactory": "root",
    "SelfCaptureStateChanged": "root",
    "SelfCaptureVadFactory": "root",
    "STABLE_KEYRING_SERVICE_NAME": "wiring_secrets_factory",
    "SyncSecretStore": "root",
    "SyncSecretStoreAdapter": "root",
}

__all__ = [
    "annotations",
    "apply_discord_issue_result_to_managed_state",
    "build_custom_vocabulary_runtime_config",
    "build_llm_provider_signature",
    "build_local_asr_session_options",
    "build_managed_identity_state_port",
    "build_openrouter_credential_runtime_config",
    "build_openrouter_release_runtime_config",
    "build_peer_capture_session_config",
    "build_peer_capture_session_config_from_vnext",
    "build_peer_stt_provider_request",
    "build_peer_stt_provider_signature",
    "build_peer_stt_provider_signature_from_vnext",
    "build_peer_stt_runtime_signature",
    "build_peer_stt_runtime_signature_from_vnext",
    "build_self_capture_session_config",
    "build_self_capture_session_config_from_vnext",
    "build_self_capture_vad_signature",
    "build_self_local_asr_transition_request",
    "build_self_stt_provider_request",
    "build_self_stt_provider_request_from_vnext",
    "build_self_stt_provider_signature",
    "build_self_stt_runtime_signature",
    "build_self_stt_runtime_signature_from_vnext",
    "build_translation_runtime_config",
    "Callable",
    "CaptureDiagnosticsAdapter",
    "CaptureOwnerFactory",
    "compose_application_runtime_logging",
    "compose_local_asr_application",
    "compose_managed_account",
    "compose_peer_application",
    "compose_peer_capture_session_owner",
    "compose_provider_runtime",
    "compose_runtime_pipeline",
    "compose_self_capture_session_owner",
    "compose_vrc_mic_sync",
    "create_desktop_overlay_policy",
    "create_gpu_provider_recovery_application_owner",
    "create_gpu_runtime_interaction_owner",
    "create_llm_provider",
    "create_llm_provider_from_resolved_config",
    "create_local_asr_cpu_repair_owner",
    "create_local_asr_diagnostics_owner",
    "create_local_asr_provisioning_owner",
    "create_local_asr_readiness_owner",
    "create_manual_typing_owner",
    "create_microphone_test_capture_adapter",
    "create_peer_capture_admission_adapter",
    "create_peer_capture_audio_loop_adapter",
    "create_peer_capture_source_adapter",
    "create_peer_capture_target_resolver_adapter",
    "create_peer_capture_vad_adapter",
    "create_peer_capture_vad_sink_adapter",
    "create_peer_stt_backend_from_resolved_config",
    "create_provider_credential_verification_interaction_owner",
    "create_provider_verifier",
    "create_secret_store",
    "create_self_capture_admission_adapter",
    "create_self_capture_audio_loop_adapter",
    "create_self_capture_source_adapter",
    "create_self_capture_vad_adapter",
    "create_self_capture_vad_sink_adapter",
    "create_stt_backend_from_resolved_config",
    "create_sync_secret_store_adapter",
    "create_vrchat_osc_presence_probe_owner",
    "create_windows_desktop_work_area",
    "DiagnosticsEnabled",
    "DISCORD_AUTH_ERROR_KEY_BY_SUBCODE",
    "DiscordManagedBrokerClientAdapter",
    "DiscordOAuthAuthAdapter",
    "DiscordOAuthCallbackRunner",
    "DiscordOAuthListenerFactory",
    "FaultProfileProvider",
    "FinalTranscriptSuppressedSink",
    "FIXED_TRANSLATION_POLICY",
    "HardwareFingerprintProvider",
    "HuggingFaceXetDownloadAdapter",
    "load_managed_openrouter_user_identifier",
    "LocalASRApplicationRuntime",
    "LocalASRChannel",
    "LocalASRProviderRuntimeFactory",
    "LocalASRProviderRuntimePort",
    "LocalASRProvisioningOwner",
    "logger",
    "MANAGED_OPENROUTER_RELEASE_SERVICE_REQUIRED_ERROR",
    "ManagedAccountComponents",
    "ManagedAuthIngressProvider",
    "ManagedAuthPersistenceCallbackFactory",
    "ManagedAuthReleaseServiceProvider",
    "ManagedAuthRuntimeAdapter",
    "ManagedAuthRuntimePresenceProvider",
    "ManagedAuthSecretStoreFactory",
    "ManagedAuthSettingsOwnerComplete",
    "ManagedAuthSettingsProvider",
    "ManagedAuthSettingsRepositoryFactory",
    "ManagedAuthSettingsSink",
    "ManagedIdentityPreflightAdapter",
    "ManagedIdentityStateAdapter",
    "ManagedLlmRuntimePort",
    "ManagedOpenRouterReleaseRuntime",
    "ManagedSTTProviderFactory",
    "ManagedTranslationContextPort",
    "ManagedTranslationFounderDialog",
    "ManagedTranslationIngressProvider",
    "ManagedTranslationPersistSettings",
    "ManagedTranslationReleaseServiceProvider",
    "ManagedTranslationRuntimeAccess",
    "ManagedTranslationRuntimeAdapter",
    "ManagedTranslationRuntimeSnapshotProvider",
    "ManagedTranslationSettingsProvider",
    "ManagedUsageRuntimeAdapter",
    "MicrophoneTestRuntime",
    "Path",
    "peer_stt_runtime_intent_from_vnext",
    "PeerApplicationRuntime",
    "PeerCaptureAdmissionPort",
    "PeerCaptureProviderAdapter",
    "PeerCaptureSessionOwner",
    "PeerCaptureTargetResolverPort",
    "project_translation_runtime_settings",
    "project_translation_runtime_settings_from_vnext",
    "provider_runtime_requires_gpu_restart",
    "ProviderChannelResetPort",
    "ProviderRuntimeComponents",
    "ProviderRuntimeEffects",
    "ProviderRuntimeSignatures",
    "ProvisioningDiagnosticSink",
    "ProvisioningStateChanged",
    "replace_translation_runtime_effective_flags",
    "replace_translation_runtime_enabled",
    "replace_translation_runtime_settings",
    "require_secret",
    "require_secret_any",
    "resolve_llm_config",
    "overlay_runtime_intent_from_vnext",
    "resolve_overlay_config",
    "resolve_overlay_config_from_vnext",
    "resolve_peer_stt_config",
    "resolve_peer_stt_runtime_config",
    "resolve_peer_stt_runtime_config_from_vnext",
    "resolve_self_stt_runtime_config",
    "ResolvedPeerSTTConfig",
    "root",
    "RuntimeCompositionComponents",
    "RuntimePipelineChannelResetRouter",
    "RuntimePipelineComponents",
    "RuntimePipelineHandle",
    "runtime_pipeline_inputs_from_vnext",
    "RuntimePipelineLauncher",
    "RuntimePipelineResourceOwner",
    "SECRETS_PASSPHRASE_ENV",
    "SecretStorePort",
    "SelfCaptureAdmissionPort",
    "SelfCaptureAudioLoop",
    "SelfCaptureDiagnosticSink",
    "SelfCaptureProviderAdapter",
    "SelfCaptureProviderRequestFactory",
    "SelfCaptureSessionOwner",
    "SelfCaptureSourceFactory",
    "SelfCaptureStateChanged",
    "SelfCaptureVadFactory",
    "STABLE_KEYRING_SERVICE_NAME",
    "SyncSecretStore",
    "SyncSecretStoreAdapter",
    "wiring_application_runtime_logging",
    "wiring_capture_runtime",
    "wiring_composition",
    "wiring_llm_factory",
    "wiring_local_asr_application",
    "wiring_local_asr_provider_runtime",
    "wiring_managed_account",
    "wiring_managed_auth_factory",
    "wiring_microphone_test",
    "wiring_overlay_factory",
    "wiring_peer_application",
    "wiring_provider_runtime",
    "wiring_provider_runtime_policy",
    "wiring_runtime_composition",
    "wiring_runtime_pipeline",
    "wiring_secrets_factory",
    "wiring_stt_factory",
    "wiring_translation_runtime_configuration",
    "wiring_vrc_mic_sync",
]


def __getattr__(name: str) -> object:
    if name in _SUBMODULES:
        return _import_module(f".{name}", __name__)
    source = _EXPORT_SOURCES.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(_import_module(f".{source}", __name__), name)
