from __future__ import annotations

from typing import Any, Protocol


class UiPresentationPort(Protocol):
    @property
    def view_dashboard(self) -> object | None: ...

    @property
    def view_settings(self) -> object | None: ...

    @property
    def view_logs(self) -> object | None: ...

    @property
    def debug_ui_preview(self) -> bool: ...

    def refresh_overlay_peer_contract(self) -> None: ...

    def apply_locale(self) -> None: ...

    def add_history_entry(self, *args: Any, **kwargs: Any) -> None: ...

    def get_event_language_codes(self) -> tuple[str | None, str | None]: ...

    def is_event_translation_enabled(self) -> bool: ...

    def get_event_stt_state(self) -> object | None: ...

    def clear_managed_auth_pending_state(self) -> None: ...

    def show_snackbar(self, *args: Any, **kwargs: Any) -> None: ...

    def on_github_star_translation_success(self) -> None: ...

    def on_telemetry_translation_success(self) -> None: ...

    def on_overlay_state_changed(self, **kwargs: Any) -> None: ...

    def on_desktop_overlay_state_changed(self, *args: Any, **kwargs: Any) -> None: ...

    def show_qq_managed_auth_dialog(self) -> None: ...

    def show_founder_letter_dialog(self) -> None: ...

    def show_local_qwen_hallucination_dialog(self) -> None: ...

    async def close_after_launch_tasks(self) -> None: ...

    async def close_github_star_prompt_runtime(self) -> None: ...

    async def close_oauth_runtime(self) -> None: ...


__all__ = ["UiPresentationPort"]
