from importlib import import_module as _import_module

_SUBMODULES = frozenset(
    {
        "local_asr_provider_runtime",
        "local_asr_provisioning",
        "local_gpu_assets",
        "local_qwen_runtime",
        "local_stt_assets",
        "local_stt_catalog",
        "local_stt_download_port",
        "local_stt_huggingface_xet_adapter",
        "local_stt_runtime_installer",
    }
)
_EXPORT_SOURCES = {
    "canonical_local_stt_language_code": "local_stt_catalog",
    "cleanup_local_stt_install_residue": "local_stt_runtime_installer",
    "default_local_stt_installed_manifest_path": "local_stt_assets",
    "default_local_stt_model_dir": "local_stt_assets",
    "default_local_stt_model_root": "local_stt_assets",
    "default_local_stt_source_for_locale": "local_stt_assets",
    "ensure_local_qwen_windows_runtime": "local_qwen_runtime",
    "ensure_local_stt_installed": "local_stt_runtime_installer",
    "HuggingFaceDownloadPort": "local_stt_download_port",
    "HuggingFaceDownloadProgress": "local_stt_download_port",
    "HuggingFaceDownloadRequest": "local_stt_download_port",
    "HuggingFaceProgressCallback": "local_stt_download_port",
    "HuggingFaceXetDownloadAdapter": "local_stt_huggingface_xet_adapter",
    "inspect_local_cpu_model_installs": "local_stt_catalog",
    "inspect_local_gpu_install": "local_gpu_assets",
    "inspect_local_stt_install_state": "local_stt_assets",
    "inspect_required_cpu_model_installs": "local_stt_catalog",
    "InstalledLocalSTTManifest": "local_stt_assets",
    "load_local_gpu_asset_manifest": "local_gpu_assets",
    "load_local_stt_asset_manifest": "local_stt_assets",
    "LOCAL_CPU_MODEL_CONTRACTS": "local_stt_catalog",
    "local_cpu_model_supports_language": "local_stt_catalog",
    "local_gpu_model_path": "local_gpu_assets",
    "LOCAL_QWEN_GPU_ENGINE": "local_gpu_assets",
    "LOCAL_QWEN_GPU_MODEL_FILENAME": "local_gpu_assets",
    "LOCAL_QWEN_GPU_MODEL_ID": "local_stt_assets",
    "LOCAL_QWEN_PACKAGED_RUNTIME_RELATIVE_DIR": "local_qwen_runtime",
    "LOCAL_STT_ENGINE": "local_stt_assets",
    "LOCAL_STT_INSTALL_DIRNAME": "local_stt_assets",
    "LOCAL_STT_INSTALLED_MANIFEST_FILENAME": "local_stt_assets",
    "LOCAL_STT_MANIFEST_RELATIVE_PATH": "local_stt_assets",
    "LOCAL_STT_MANIFEST_RELATIVE_PATHS": "local_stt_assets",
    "LOCAL_STT_MODEL_ID": "local_stt_assets",
    "LocalASRInstallRequest": "local_asr_provisioning",
    "LocalASRInstallResult": "local_asr_provisioning",
    "LocalASRInstallResultHandler": "local_asr_provisioning",
    "LocalASRIntegrityStatus": "local_asr_provisioning",
    "LocalASRModelProvisioningState": "local_asr_provisioning",
    "LocalASROperationStatus": "local_asr_provisioning",
    "LocalASRProviderRuntimeCallbacks": "local_asr_provider_runtime",
    "LocalASRProviderRuntimeFactoryPort": "local_asr_provider_runtime",
    "LocalASRProviderRuntimePort": "local_asr_provider_runtime",
    "LocalASRProviderRuntimeSnapshot": "local_asr_provider_runtime",
    "LocalASRProvisioningActivity": "local_asr_provisioning",
    "LocalASRProvisioningBackend": "local_asr_provisioning",
    "LocalASRProvisioningDiagnostic": "local_asr_provisioning",
    "LocalASRProvisioningPort": "local_asr_provisioning",
    "LocalASRProvisioningSnapshot": "local_asr_provisioning",
    "LocalASRProvisioningStatus": "local_asr_provisioning",
    "LocalCPUAutoUnavailableError": "local_stt_catalog",
    "LocalCPUInstallSnapshot": "local_stt_catalog",
    "LocalCPUModelContract": "local_stt_catalog",
    "LocalCPUModelInstall": "local_stt_catalog",
    "LocalGPUInstallSnapshot": "local_gpu_assets",
    "LocalGPUOptInStatus": "local_gpu_assets",
    "LocalParakeetSherpaLoadError": "local_stt_assets",
    "LocalQwenRuntimeBootstrapError": "local_qwen_runtime",
    "LocalQwenSherpaLoadError": "local_stt_assets",
    "LocalSTTAssetError": "local_stt_assets",
    "LocalSTTAssetFile": "local_stt_assets",
    "LocalSTTAssetManifest": "local_stt_assets",
    "LocalSTTAssetSource": "local_stt_assets",
    "LocalSTTDownloadPortCancelled": "local_stt_download_port",
    "LocalSTTDownloadPortError": "local_stt_download_port",
    "LocalSTTInstallState": "local_stt_assets",
    "LocalSTTInstallStatus": "local_stt_assets",
    "LocalSTTManifestInvalidError": "local_stt_assets",
    "LocalSTTModelMissingError": "local_stt_assets",
    "LocalSTTProvisioningLease": "local_stt_runtime_installer",
    "LocalSTTRuntimeInstallCancelled": "local_stt_runtime_installer",
    "LocalSTTRuntimeInstallError": "local_stt_runtime_installer",
    "LocalSTTUnsupportedLanguageError": "local_stt_catalog",
    "logger": "local_qwen_runtime",
    "PARAKEET_JAPANESE_MODEL_ID": "local_stt_assets",
    "PARAKEET_JAPANESE_SUPPORTED_LANGUAGE_CODES": "local_stt_catalog",
    "PARAKEET_V3_MODEL_ID": "local_stt_assets",
    "PARAKEET_V3_SUPPORTED_LANGUAGE_CODES": "local_stt_catalog",
    "ProviderGpuRuntimePort": "local_asr_provider_runtime",
    "ProviderRuntimeBuildRequest": "local_asr_provider_runtime",
    "ProviderRuntimeChannel": "local_asr_provider_runtime",
    "ProviderRuntimeChannelPhase": "local_asr_provider_runtime",
    "ProviderRuntimeChannelSnapshot": "local_asr_provider_runtime",
    "ProviderRuntimeDiagnostic": "local_asr_provider_runtime",
    "ProviderRuntimeEventHandler": "local_asr_provider_runtime",
    "ProviderRuntimeExceptionHandler": "local_asr_provider_runtime",
    "ProviderRuntimeGpuPhase": "local_asr_provider_runtime",
    "ProviderRuntimeGpuRecoveryRequest": "local_asr_provider_runtime",
    "ProviderRuntimeGpuSnapshot": "local_asr_provider_runtime",
    "ProviderRuntimeMutationResult": "local_asr_provider_runtime",
    "ProviderRuntimeMutationStatus": "local_asr_provider_runtime",
    "ProviderRuntimeProviderFactoryPort": "local_asr_provider_runtime",
    "ProviderRuntimeRecoveryChannel": "local_asr_provider_runtime",
    "ProviderRuntimeRecoveryQuiesce": "local_asr_provider_runtime",
    "ProviderRuntimeReleaseMode": "local_asr_provider_runtime",
    "ProviderRuntimeTerminalFailureSink": "local_asr_provider_runtime",
    "QWEN_06B_SUPPORTED_LANGUAGE_CODES": "local_stt_catalog",
    "REQUIRED_CPU_LOCAL_STT_MODEL_IDS": "local_stt_assets",
    "REQUIRED_LOCAL_QWEN_RUNTIME_DLLS": "local_qwen_runtime",
    "resolve_cpu_auto_model": "local_stt_catalog",
    "resolve_local_qwen_runtime_dir": "local_qwen_runtime",
    "run_huggingface_xet_worker": "local_stt_huggingface_xet_adapter",
    "RuntimeLocalSTTStatus": "local_stt_runtime_installer",
    "RuntimeLocalSTTStatusUpdate": "local_stt_runtime_installer",
    "StatusCallback": "local_stt_runtime_installer",
    "validate_local_stt_install": "local_stt_assets",
    "validate_local_stt_runtime_ready": "local_stt_assets",
    "WorkerCommandFactory": "local_stt_huggingface_xet_adapter",
}

__all__ = [
    "canonical_local_stt_language_code",
    "cleanup_local_stt_install_residue",
    "default_local_stt_installed_manifest_path",
    "default_local_stt_model_dir",
    "default_local_stt_model_root",
    "default_local_stt_source_for_locale",
    "ensure_local_qwen_windows_runtime",
    "ensure_local_stt_installed",
    "HuggingFaceDownloadPort",
    "HuggingFaceDownloadProgress",
    "HuggingFaceDownloadRequest",
    "HuggingFaceProgressCallback",
    "HuggingFaceXetDownloadAdapter",
    "inspect_local_cpu_model_installs",
    "inspect_local_gpu_install",
    "inspect_local_stt_install_state",
    "inspect_required_cpu_model_installs",
    "InstalledLocalSTTManifest",
    "load_local_gpu_asset_manifest",
    "load_local_stt_asset_manifest",
    "local_asr_provider_runtime",
    "local_asr_provisioning",
    "LOCAL_CPU_MODEL_CONTRACTS",
    "local_cpu_model_supports_language",
    "local_gpu_assets",
    "local_gpu_model_path",
    "LOCAL_QWEN_GPU_ENGINE",
    "LOCAL_QWEN_GPU_MODEL_FILENAME",
    "LOCAL_QWEN_GPU_MODEL_ID",
    "LOCAL_QWEN_PACKAGED_RUNTIME_RELATIVE_DIR",
    "local_qwen_runtime",
    "local_stt_assets",
    "local_stt_catalog",
    "local_stt_download_port",
    "LOCAL_STT_ENGINE",
    "local_stt_huggingface_xet_adapter",
    "LOCAL_STT_INSTALL_DIRNAME",
    "LOCAL_STT_INSTALLED_MANIFEST_FILENAME",
    "LOCAL_STT_MANIFEST_RELATIVE_PATH",
    "LOCAL_STT_MANIFEST_RELATIVE_PATHS",
    "LOCAL_STT_MODEL_ID",
    "local_stt_runtime_installer",
    "LocalASRInstallRequest",
    "LocalASRInstallResult",
    "LocalASRInstallResultHandler",
    "LocalASRIntegrityStatus",
    "LocalASRModelProvisioningState",
    "LocalASROperationStatus",
    "LocalASRProviderRuntimeCallbacks",
    "LocalASRProviderRuntimeFactoryPort",
    "LocalASRProviderRuntimePort",
    "LocalASRProviderRuntimeSnapshot",
    "LocalASRProvisioningActivity",
    "LocalASRProvisioningBackend",
    "LocalASRProvisioningDiagnostic",
    "LocalASRProvisioningPort",
    "LocalASRProvisioningSnapshot",
    "LocalASRProvisioningStatus",
    "LocalCPUAutoUnavailableError",
    "LocalCPUInstallSnapshot",
    "LocalCPUModelContract",
    "LocalCPUModelInstall",
    "LocalGPUInstallSnapshot",
    "LocalGPUOptInStatus",
    "LocalParakeetSherpaLoadError",
    "LocalQwenRuntimeBootstrapError",
    "LocalQwenSherpaLoadError",
    "LocalSTTAssetError",
    "LocalSTTAssetFile",
    "LocalSTTAssetManifest",
    "LocalSTTAssetSource",
    "LocalSTTDownloadPortCancelled",
    "LocalSTTDownloadPortError",
    "LocalSTTInstallState",
    "LocalSTTInstallStatus",
    "LocalSTTManifestInvalidError",
    "LocalSTTModelMissingError",
    "LocalSTTProvisioningLease",
    "LocalSTTRuntimeInstallCancelled",
    "LocalSTTRuntimeInstallError",
    "LocalSTTUnsupportedLanguageError",
    "logger",
    "PARAKEET_JAPANESE_MODEL_ID",
    "PARAKEET_JAPANESE_SUPPORTED_LANGUAGE_CODES",
    "PARAKEET_V3_MODEL_ID",
    "PARAKEET_V3_SUPPORTED_LANGUAGE_CODES",
    "ProviderGpuRuntimePort",
    "ProviderRuntimeBuildRequest",
    "ProviderRuntimeChannel",
    "ProviderRuntimeChannelPhase",
    "ProviderRuntimeChannelSnapshot",
    "ProviderRuntimeDiagnostic",
    "ProviderRuntimeEventHandler",
    "ProviderRuntimeExceptionHandler",
    "ProviderRuntimeGpuPhase",
    "ProviderRuntimeGpuRecoveryRequest",
    "ProviderRuntimeGpuSnapshot",
    "ProviderRuntimeMutationResult",
    "ProviderRuntimeMutationStatus",
    "ProviderRuntimeProviderFactoryPort",
    "ProviderRuntimeRecoveryChannel",
    "ProviderRuntimeRecoveryQuiesce",
    "ProviderRuntimeReleaseMode",
    "ProviderRuntimeTerminalFailureSink",
    "QWEN_06B_SUPPORTED_LANGUAGE_CODES",
    "REQUIRED_CPU_LOCAL_STT_MODEL_IDS",
    "REQUIRED_LOCAL_QWEN_RUNTIME_DLLS",
    "resolve_cpu_auto_model",
    "resolve_local_qwen_runtime_dir",
    "run_huggingface_xet_worker",
    "RuntimeLocalSTTStatus",
    "RuntimeLocalSTTStatusUpdate",
    "StatusCallback",
    "validate_local_stt_install",
    "validate_local_stt_runtime_ready",
    "WorkerCommandFactory",
]


def __getattr__(name: str) -> object:
    if name in _SUBMODULES:
        return _import_module(f".{name}", __name__)
    source = _EXPORT_SOURCES.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(_import_module(f".{source}", __name__), name)
