import sys as _sys
from importlib import import_module as _import_module

from puripuly_heart.app import services as _parent

for _short in (
    "managed_auth",
    "managed_auth_claims",
    "managed_connection_auth",
    "managed_key_delivery_ack",
    "managed_status_refresh",
    "managed_usage",
):
    _module = _import_module(f".{_short}", __name__)
    _sys.modules[f"puripuly_heart.app.services.{_short}"] = _module
    setattr(_parent, _short, _module)
del _module, _short

from .managed_auth import (
    QQ_AUTH_DIALOG_MESSAGE_KEY_BY_SERVICE_KEY,
    ManagedAuthDiscordExecutor,
    ManagedAuthExecutionResult,
    ManagedAuthLogSink,
    ManagedAuthMessageSink,
    ManagedAuthOwner,
    ManagedAuthPendingSink,
    ManagedAuthQqExecutor,
    ManagedAuthResultSink,
    ManagedAuthRuntimeEnsurer,
    ManagedAuthState,
    ManagedAuthStateProvider,
    ManagedAuthUsageRefreshSink,
    ManagedAuthUsageViewSink,
)
from .managed_auth_claims import (
    MANAGED_AUTH_CLAIM_SOURCE_DISCORD,
    MANAGED_AUTH_CLAIM_SOURCE_QQ,
    MANAGED_AUTH_CLAIM_SOURCES,
    OPENROUTER_MANAGED_API_KEY_SECRET,
    OPENROUTER_MANAGED_QQ_API_KEY_SECRET,
    OPENROUTER_MANAGED_USER_ID_MAX_LENGTH,
    OPENROUTER_MANAGED_USER_ID_SECRET,
    OPENROUTER_MANAGED_USER_INSTALLATION_ID_SECRET,
    ManagedAuthClaimGuard,
    local_managed_auth_blocking_source,
    normalize_managed_claim_source,
    normalize_managed_claim_sources,
    record_local_managed_claim_source,
)
from .managed_connection_auth import (
    ManagedConnectionAuthRequest,
    ManagedConnectionAuthService,
)
from .managed_key_delivery_ack import (
    ACK_SOURCE_DISCORD,
    ACK_SOURCE_QQ,
    DISCORD_MANAGED_DELIVERY_ACK_TOKEN_SECRET,
    QQ_MANAGED_DELIVERY_ACK_TOKEN_SECRET,
    ManagedKeyDeliveryAckService,
    ManagedKeyDeliveryAckServiceResult,
    ManagedKeyDeliveryAckTokenClearError,
    ManagedKeyDeliveryAckTokenStoreError,
    clear_pending_ack_in_settings_values,
    pending_ack_metadata_settings_values,
    secret_key_for_ack_source,
    store_pending_ack_in_settings_values,
)
from .managed_status_refresh import (
    ManagedStatusRefreshDiagnosticsSink,
    ManagedStatusRefreshOwner,
    ManagedStatusRefreshWork,
)
from .managed_usage import (
    ManagedUsageAutoShowFounderLetterProvider,
    ManagedUsageDisableTranslationSink,
    ManagedUsageMetadataFetcher,
    ManagedUsageMetadataResult,
    ManagedUsageOwner,
    ManagedUsagePendingSink,
    ManagedUsageReferralNormalizer,
    ManagedUsageReleaseServiceProvider,
    ManagedUsageState,
    ManagedUsageStateProvider,
    ManagedUsageViewSink,
    ManagedUsageViewState,
    ManagedUsageWarningSink,
)

__all__ = [
    "ACK_SOURCE_DISCORD",
    "ACK_SOURCE_QQ",
    "DISCORD_MANAGED_DELIVERY_ACK_TOKEN_SECRET",
    "MANAGED_AUTH_CLAIM_SOURCES",
    "MANAGED_AUTH_CLAIM_SOURCE_DISCORD",
    "MANAGED_AUTH_CLAIM_SOURCE_QQ",
    "ManagedAuthClaimGuard",
    "ManagedAuthDiscordExecutor",
    "ManagedAuthExecutionResult",
    "ManagedAuthLogSink",
    "ManagedAuthMessageSink",
    "ManagedAuthOwner",
    "ManagedAuthPendingSink",
    "ManagedAuthQqExecutor",
    "ManagedAuthResultSink",
    "ManagedAuthRuntimeEnsurer",
    "ManagedAuthState",
    "ManagedAuthStateProvider",
    "ManagedAuthUsageRefreshSink",
    "ManagedAuthUsageViewSink",
    "ManagedConnectionAuthRequest",
    "ManagedConnectionAuthService",
    "ManagedKeyDeliveryAckService",
    "ManagedKeyDeliveryAckServiceResult",
    "ManagedKeyDeliveryAckTokenClearError",
    "ManagedKeyDeliveryAckTokenStoreError",
    "ManagedStatusRefreshDiagnosticsSink",
    "ManagedStatusRefreshOwner",
    "ManagedStatusRefreshWork",
    "ManagedUsageAutoShowFounderLetterProvider",
    "ManagedUsageDisableTranslationSink",
    "ManagedUsageMetadataFetcher",
    "ManagedUsageMetadataResult",
    "ManagedUsageOwner",
    "ManagedUsagePendingSink",
    "ManagedUsageReferralNormalizer",
    "ManagedUsageReleaseServiceProvider",
    "ManagedUsageState",
    "ManagedUsageStateProvider",
    "ManagedUsageViewSink",
    "ManagedUsageViewState",
    "ManagedUsageWarningSink",
    "OPENROUTER_MANAGED_API_KEY_SECRET",
    "OPENROUTER_MANAGED_QQ_API_KEY_SECRET",
    "OPENROUTER_MANAGED_USER_ID_MAX_LENGTH",
    "OPENROUTER_MANAGED_USER_ID_SECRET",
    "OPENROUTER_MANAGED_USER_INSTALLATION_ID_SECRET",
    "QQ_AUTH_DIALOG_MESSAGE_KEY_BY_SERVICE_KEY",
    "QQ_MANAGED_DELIVERY_ACK_TOKEN_SECRET",
    "clear_pending_ack_in_settings_values",
    "local_managed_auth_blocking_source",
    "managed_auth",
    "managed_auth_claims",
    "managed_connection_auth",
    "managed_key_delivery_ack",
    "managed_status_refresh",
    "managed_usage",
    "normalize_managed_claim_source",
    "normalize_managed_claim_sources",
    "pending_ack_metadata_settings_values",
    "record_local_managed_claim_source",
    "secret_key_for_ack_source",
    "store_pending_ack_in_settings_values",
]
