from importlib import import_module as _import_module

_SUBMODULES = frozenset(
    {
        "provider_credential_verification",
        "provider_runtime_apply",
        "provider_secret_change",
        "provider_settings",
        "provider_verification_binding",
    }
)
_EXPORT_SOURCES = {
    "LlmProviderAvailabilitySink": "provider_runtime_apply",
    "LlmProviderFactory": "provider_runtime_apply",
    "LlmProviderMessageSink": "provider_runtime_apply",
    "LlmProviderRebuildContext": "provider_runtime_apply",
    "LlmProviderRebuildContextProvider": "provider_runtime_apply",
    "LlmProviderRebuildOwner": "provider_runtime_apply",
    "LlmProviderReplace": "provider_runtime_apply",
    "NoopRuntimeApply": "provider_runtime_apply",
    "OverlayOscOutputRuntimeApplyAdapter": "provider_runtime_apply",
    "PROVIDER_CREDENTIAL_EMPTY": "provider_credential_verification",
    "PROVIDER_CREDENTIAL_ERROR": "provider_credential_verification",
    "PROVIDER_CREDENTIAL_FAILED": "provider_credential_verification",
    "PROVIDER_CREDENTIAL_MODEL_UNAVAILABLE": "provider_credential_verification",
    "PROVIDER_CREDENTIAL_UNKNOWN": "provider_credential_verification",
    "PROVIDER_CREDENTIAL_VERIFIED": "provider_credential_verification",
    "provider_verification_context": "provider_settings",
    "ProviderActiveSecretProvider": "provider_settings",
    "ProviderApplicationOwner": "provider_settings",
    "ProviderCredentialSelectedModelProvider": "provider_credential_verification",
    "ProviderCredentialVerificationDiagnosticsSink": "provider_credential_verification",
    "ProviderCredentialVerificationErrorSink": "provider_credential_verification",
    "ProviderCredentialVerificationInteractionOwner": "provider_credential_verification",
    "ProviderCredentialVerificationOutcome": "provider_credential_verification",
    "ProviderCredentialVerificationOwner": "provider_credential_verification",
    "ProviderCredentialVerificationRequest": "provider_credential_verification",
    "ProviderCredentialVerificationStatus": "provider_credential_verification",
    "ProviderOrder24PatchProvider": "provider_settings",
    "ProviderRuntimeApplyAdapter": "provider_runtime_apply",
    "ProviderRuntimeApplyPlan": "provider_runtime_apply",
    "ProviderRuntimeAsyncEffect": "provider_runtime_apply",
    "ProviderRuntimeCommonEffect": "provider_runtime_apply",
    "ProviderRuntimeGpuEffect": "provider_runtime_apply",
    "ProviderRuntimeGpuRestartDecision": "provider_runtime_apply",
    "ProviderRuntimeOwner": "provider_runtime_apply",
    "ProviderRuntimePeerSignatureBuilder": "provider_runtime_apply",
    "ProviderRuntimeRetrySink": "provider_runtime_apply",
    "ProviderRuntimeSettingsProvider": "provider_runtime_apply",
    "ProviderRuntimeSignatureBuilder": "provider_runtime_apply",
    "ProviderRuntimeSignatureCacheProvider": "provider_runtime_apply",
    "ProviderRuntimeSignatureSink": "provider_runtime_apply",
    "ProviderRuntimeState": "provider_runtime_apply",
    "ProviderRuntimeStateProvider": "provider_runtime_apply",
    "ProviderSecretChangeExecution": "provider_secret_change",
    "ProviderSecretChangeExecutionFactory": "provider_secret_change",
    "ProviderSecretChangeOwner": "provider_secret_change",
    "ProviderSecretChangeRequest": "provider_secret_change",
    "ProviderSecretChangeResultHandler": "provider_secret_change",
    "ProviderSecretChangeTransactionPort": "provider_secret_change",
    "ProviderSecretStoreFactory": "provider_settings",
    "ProviderSettingsAsyncEffect": "provider_settings",
    "ProviderSettingsCompensation": "provider_settings",
    "ProviderSettingsMerge": "provider_settings",
    "ProviderSettingsMutationServiceProvider": "provider_settings",
    "ProviderSettingsOwner": "provider_settings",
    "ProviderSettingsPredicate": "provider_settings",
    "ProviderSettingsRoute": "provider_settings",
    "ProviderSettingsSaveFailureSink": "provider_settings",
    "ProviderSettingsSync": "provider_settings",
    "ProviderStrictSettingsSaveFailed": "provider_settings",
    "ProviderSupersededSettingsConsumer": "provider_settings",
    "ProviderVerificationBindingOwner": "provider_verification_binding",
    "ProviderVerificationContextProvider": "provider_verification_binding",
    "SettingsRuntimeApplyEffect": "provider_runtime_apply",
    "SettingsRuntimeStateProvider": "provider_runtime_apply",
    "SttLanguageAudioRuntimeApplyAdapter": "provider_runtime_apply",
    "UiPromptClipboardStateRuntimeApplyAdapter": "provider_runtime_apply",
}

__all__ = [
    "LlmProviderAvailabilitySink",
    "LlmProviderFactory",
    "LlmProviderMessageSink",
    "LlmProviderRebuildContext",
    "LlmProviderRebuildContextProvider",
    "LlmProviderRebuildOwner",
    "LlmProviderReplace",
    "NoopRuntimeApply",
    "OverlayOscOutputRuntimeApplyAdapter",
    "PROVIDER_CREDENTIAL_EMPTY",
    "PROVIDER_CREDENTIAL_ERROR",
    "PROVIDER_CREDENTIAL_FAILED",
    "PROVIDER_CREDENTIAL_MODEL_UNAVAILABLE",
    "PROVIDER_CREDENTIAL_UNKNOWN",
    "provider_credential_verification",
    "PROVIDER_CREDENTIAL_VERIFIED",
    "provider_runtime_apply",
    "provider_secret_change",
    "provider_settings",
    "provider_verification_binding",
    "provider_verification_context",
    "ProviderActiveSecretProvider",
    "ProviderApplicationOwner",
    "ProviderCredentialSelectedModelProvider",
    "ProviderCredentialVerificationDiagnosticsSink",
    "ProviderCredentialVerificationErrorSink",
    "ProviderCredentialVerificationInteractionOwner",
    "ProviderCredentialVerificationOutcome",
    "ProviderCredentialVerificationOwner",
    "ProviderCredentialVerificationRequest",
    "ProviderCredentialVerificationStatus",
    "ProviderOrder24PatchProvider",
    "ProviderRuntimeApplyAdapter",
    "ProviderRuntimeApplyPlan",
    "ProviderRuntimeAsyncEffect",
    "ProviderRuntimeCommonEffect",
    "ProviderRuntimeGpuEffect",
    "ProviderRuntimeGpuRestartDecision",
    "ProviderRuntimeOwner",
    "ProviderRuntimePeerSignatureBuilder",
    "ProviderRuntimeRetrySink",
    "ProviderRuntimeSettingsProvider",
    "ProviderRuntimeSignatureBuilder",
    "ProviderRuntimeSignatureCacheProvider",
    "ProviderRuntimeSignatureSink",
    "ProviderRuntimeState",
    "ProviderRuntimeStateProvider",
    "ProviderSecretChangeExecution",
    "ProviderSecretChangeExecutionFactory",
    "ProviderSecretChangeOwner",
    "ProviderSecretChangeRequest",
    "ProviderSecretChangeResultHandler",
    "ProviderSecretChangeTransactionPort",
    "ProviderSecretStoreFactory",
    "ProviderSettingsAsyncEffect",
    "ProviderSettingsCompensation",
    "ProviderSettingsMerge",
    "ProviderSettingsMutationServiceProvider",
    "ProviderSettingsOwner",
    "ProviderSettingsPredicate",
    "ProviderSettingsRoute",
    "ProviderSettingsSaveFailureSink",
    "ProviderSettingsSync",
    "ProviderStrictSettingsSaveFailed",
    "ProviderSupersededSettingsConsumer",
    "ProviderVerificationBindingOwner",
    "ProviderVerificationContextProvider",
    "SettingsRuntimeApplyEffect",
    "SettingsRuntimeStateProvider",
    "SttLanguageAudioRuntimeApplyAdapter",
    "UiPromptClipboardStateRuntimeApplyAdapter",
]


def __getattr__(name: str) -> object:
    if name in _SUBMODULES:
        return _import_module(f".{name}", __name__)
    source = _EXPORT_SOURCES.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(_import_module(f".{source}", __name__), name)
