import sys as _sys
from importlib import import_module as _import_module

from puripuly_heart import core as _parent

for _short in (
    "openrouter_metadata",
    "openrouter_credentials",
    "openrouter_pkce",
    "openrouter_handoff",
    "managed_openrouter_release",
    "managed_openrouter_broker_client",
):
    _module = _import_module(f".{_short}", __name__)
    _sys.modules[f"puripuly_heart.core.{_short}"] = _module
    setattr(_parent, _short, _module)
del _module, _short

from .managed_openrouter_broker_client import (
    PUBLIC_ERROR_CLASSES,
    PUBLIC_ERROR_CODES,
    RETRYABLE_ERROR_CLASS,
    RETRYABLE_ERROR_CODE,
    HttpManagedOpenRouterBrokerClient,
)
from .managed_openrouter_release import (
    BINDING_MISMATCH_SUBCODES,
    DISCORD_MANAGED_DELIVERY_ACK_TOKEN_SECRET,
    MANAGED_OPENROUTER_TRIAL_BUDGET_USD,
    QQ_MANAGED_DELIVERY_ACK_TOKEN_SECRET,
    DiscordOAuthCallbackRunner,
    DiscordOAuthListenerFactory,
    HardwareFingerprintProvider,
    ManagedOpenRouterChallengeSuccess,
    ManagedOpenRouterDelegateFactory,
    ManagedOpenRouterDiscordStartSuccess,
    ManagedOpenRouterFingerprintSalt,
    ManagedOpenRouterIssueSuccess,
    ManagedOpenRouterLLMProvider,
    ManagedOpenRouterPreflightStop,
    ManagedOpenRouterReleaseBehavior,
    ManagedOpenRouterReleaseClient,
    ManagedOpenRouterReleaseDiagnostics,
    ManagedOpenRouterReleaseError,
    ManagedOpenRouterReleaseResult,
    ManagedOpenRouterReleaseService,
    ManagedOpenRouterStatusRefreshResult,
    ManagedOpenRouterTrialStatusSuccess,
    ManagedOpenRouterUserFacingError,
    ManagedOpenRouterVerifySuccess,
    OpenRouterReleaseRuntimeConfig,
    TalkTogetherPassStatus,
    UnavailableManagedOpenRouterReleaseClient,
    format_managed_openrouter_diagnostics,
)
from .openrouter_credentials import (
    OPENROUTER_BYOK_API_KEY_ENV,
    OPENROUTER_BYOK_API_KEY_SECRET,
    OPENROUTER_MANAGED_API_KEY_SECRET,
    OPENROUTER_MANAGED_QQ_API_KEY_SECRET,
    OPENROUTER_MANAGED_USER_ID_MAX_LENGTH,
    OPENROUTER_MANAGED_USER_ID_SECRET,
    OPENROUTER_MANAGED_USER_INSTALLATION_ID_SECRET,
    OpenRouterCredentialResolution,
    OpenRouterCredentialRuntimeConfig,
    OpenRouterManagedRecoveryAction,
    OpenRouterManagedRecoveryResult,
    best_effort_clear_managed_openrouter_user_identifier,
    best_effort_store_managed_openrouter_user_identifier,
    clear_temporary_managed_release_state,
    handle_managed_availability,
    handle_managed_release_error,
    load_managed_openrouter_user_identifier,
    normalize_managed_openrouter_user_identifier,
    require_openrouter_execution_api_key,
    resolve_openrouter_credentials,
)
from .openrouter_handoff import (
    MANAGED_EFFECTIVE_EXHAUSTION_USD,
    is_effectively_exhausted,
    mark_founder_letter_shown,
    should_auto_show_founder_letter,
    store_managed_entitlement_snapshot,
)
from .openrouter_metadata import OpenRouterKeyMetadata
from .openrouter_pkce import (
    CALLBACK_TIMEOUT_SECONDS,
    OPENROUTER_AUTH_EXCHANGE_URL,
    OPENROUTER_AUTH_URL,
    PKCE_CHALLENGE_METHOD,
    OpenRouterPKCEClient,
    OpenRouterPKCEExchangeResult,
    OpenRouterPKCESession,
)

__all__ = [
    "BINDING_MISMATCH_SUBCODES",
    "CALLBACK_TIMEOUT_SECONDS",
    "DISCORD_MANAGED_DELIVERY_ACK_TOKEN_SECRET",
    "DiscordOAuthCallbackRunner",
    "DiscordOAuthListenerFactory",
    "HardwareFingerprintProvider",
    "HttpManagedOpenRouterBrokerClient",
    "MANAGED_EFFECTIVE_EXHAUSTION_USD",
    "MANAGED_OPENROUTER_TRIAL_BUDGET_USD",
    "ManagedOpenRouterChallengeSuccess",
    "ManagedOpenRouterDelegateFactory",
    "ManagedOpenRouterDiscordStartSuccess",
    "ManagedOpenRouterFingerprintSalt",
    "ManagedOpenRouterIssueSuccess",
    "ManagedOpenRouterLLMProvider",
    "ManagedOpenRouterPreflightStop",
    "ManagedOpenRouterReleaseBehavior",
    "ManagedOpenRouterReleaseClient",
    "ManagedOpenRouterReleaseDiagnostics",
    "ManagedOpenRouterReleaseError",
    "ManagedOpenRouterReleaseResult",
    "ManagedOpenRouterReleaseService",
    "ManagedOpenRouterStatusRefreshResult",
    "ManagedOpenRouterTrialStatusSuccess",
    "ManagedOpenRouterUserFacingError",
    "ManagedOpenRouterVerifySuccess",
    "OPENROUTER_AUTH_EXCHANGE_URL",
    "OPENROUTER_AUTH_URL",
    "OPENROUTER_BYOK_API_KEY_ENV",
    "OPENROUTER_BYOK_API_KEY_SECRET",
    "OPENROUTER_MANAGED_API_KEY_SECRET",
    "OPENROUTER_MANAGED_QQ_API_KEY_SECRET",
    "OPENROUTER_MANAGED_USER_ID_MAX_LENGTH",
    "OPENROUTER_MANAGED_USER_ID_SECRET",
    "OPENROUTER_MANAGED_USER_INSTALLATION_ID_SECRET",
    "OpenRouterCredentialResolution",
    "OpenRouterCredentialRuntimeConfig",
    "OpenRouterKeyMetadata",
    "OpenRouterManagedRecoveryAction",
    "OpenRouterManagedRecoveryResult",
    "OpenRouterPKCEClient",
    "OpenRouterPKCEExchangeResult",
    "OpenRouterPKCESession",
    "OpenRouterReleaseRuntimeConfig",
    "PKCE_CHALLENGE_METHOD",
    "PUBLIC_ERROR_CLASSES",
    "PUBLIC_ERROR_CODES",
    "QQ_MANAGED_DELIVERY_ACK_TOKEN_SECRET",
    "RETRYABLE_ERROR_CLASS",
    "RETRYABLE_ERROR_CODE",
    "TalkTogetherPassStatus",
    "UnavailableManagedOpenRouterReleaseClient",
    "best_effort_clear_managed_openrouter_user_identifier",
    "best_effort_store_managed_openrouter_user_identifier",
    "clear_temporary_managed_release_state",
    "format_managed_openrouter_diagnostics",
    "handle_managed_availability",
    "handle_managed_release_error",
    "is_effectively_exhausted",
    "load_managed_openrouter_user_identifier",
    "managed_openrouter_broker_client",
    "managed_openrouter_release",
    "mark_founder_letter_shown",
    "normalize_managed_openrouter_user_identifier",
    "openrouter_credentials",
    "openrouter_handoff",
    "openrouter_metadata",
    "openrouter_pkce",
    "require_openrouter_execution_api_key",
    "resolve_openrouter_credentials",
    "should_auto_show_founder_letter",
    "store_managed_entitlement_snapshot",
]
