from importlib import import_module as _import_module

_SUBMODULES = frozenset(
    {
        "managed_openrouter_broker_client",
        "managed_openrouter_release",
        "openrouter_credentials",
        "openrouter_handoff",
        "openrouter_metadata",
        "openrouter_pkce",
    }
)
_EXPORT_SOURCES = {
    "best_effort_clear_managed_openrouter_user_identifier": "openrouter_credentials",
    "best_effort_store_managed_openrouter_user_identifier": "openrouter_credentials",
    "BINDING_MISMATCH_SUBCODES": "managed_openrouter_release",
    "CALLBACK_TIMEOUT_SECONDS": "openrouter_pkce",
    "clear_temporary_managed_release_state": "openrouter_credentials",
    "DISCORD_MANAGED_DELIVERY_ACK_TOKEN_SECRET": "managed_openrouter_release",
    "DiscordOAuthCallbackRunner": "managed_openrouter_release",
    "DiscordOAuthListenerFactory": "managed_openrouter_release",
    "format_managed_openrouter_diagnostics": "managed_openrouter_release",
    "handle_managed_availability": "openrouter_credentials",
    "handle_managed_release_error": "openrouter_credentials",
    "HardwareFingerprintProvider": "managed_openrouter_release",
    "HttpManagedOpenRouterBrokerClient": "managed_openrouter_broker_client",
    "is_effectively_exhausted": "openrouter_handoff",
    "load_managed_openrouter_user_identifier": "openrouter_credentials",
    "MANAGED_EFFECTIVE_EXHAUSTION_USD": "openrouter_handoff",
    "MANAGED_OPENROUTER_TRIAL_BUDGET_USD": "managed_openrouter_release",
    "ManagedOpenRouterChallengeSuccess": "managed_openrouter_release",
    "ManagedOpenRouterDelegateFactory": "managed_openrouter_release",
    "ManagedOpenRouterDiscordStartSuccess": "managed_openrouter_release",
    "ManagedOpenRouterFingerprintSalt": "managed_openrouter_release",
    "ManagedOpenRouterIssueSuccess": "managed_openrouter_release",
    "ManagedOpenRouterLLMProvider": "managed_openrouter_release",
    "ManagedOpenRouterPreflightStop": "managed_openrouter_release",
    "ManagedOpenRouterReleaseBehavior": "managed_openrouter_release",
    "ManagedOpenRouterReleaseClient": "managed_openrouter_release",
    "ManagedOpenRouterReleaseDiagnostics": "managed_openrouter_release",
    "ManagedOpenRouterReleaseError": "managed_openrouter_release",
    "ManagedOpenRouterReleaseResult": "managed_openrouter_release",
    "ManagedOpenRouterReleaseService": "managed_openrouter_release",
    "ManagedOpenRouterStatusRefreshResult": "managed_openrouter_release",
    "ManagedOpenRouterTrialStatusSuccess": "managed_openrouter_release",
    "ManagedOpenRouterUserFacingError": "managed_openrouter_release",
    "ManagedOpenRouterVerifySuccess": "managed_openrouter_release",
    "mark_founder_letter_shown": "openrouter_handoff",
    "normalize_managed_openrouter_user_identifier": "openrouter_credentials",
    "OPENROUTER_AUTH_EXCHANGE_URL": "openrouter_pkce",
    "OPENROUTER_AUTH_URL": "openrouter_pkce",
    "OPENROUTER_BYOK_API_KEY_ENV": "openrouter_credentials",
    "OPENROUTER_BYOK_API_KEY_SECRET": "openrouter_credentials",
    "OPENROUTER_MANAGED_API_KEY_SECRET": "openrouter_credentials",
    "OPENROUTER_MANAGED_QQ_API_KEY_SECRET": "openrouter_credentials",
    "OPENROUTER_MANAGED_USER_ID_MAX_LENGTH": "openrouter_credentials",
    "OPENROUTER_MANAGED_USER_ID_SECRET": "openrouter_credentials",
    "OPENROUTER_MANAGED_USER_INSTALLATION_ID_SECRET": "openrouter_credentials",
    "OpenRouterCredentialResolution": "openrouter_credentials",
    "OpenRouterCredentialRuntimeConfig": "openrouter_credentials",
    "OpenRouterKeyMetadata": "openrouter_metadata",
    "OpenRouterManagedRecoveryAction": "openrouter_credentials",
    "OpenRouterManagedRecoveryResult": "openrouter_credentials",
    "OpenRouterPKCEClient": "openrouter_pkce",
    "OpenRouterPKCEExchangeResult": "openrouter_pkce",
    "OpenRouterPKCESession": "openrouter_pkce",
    "OpenRouterReleaseRuntimeConfig": "managed_openrouter_release",
    "PKCE_CHALLENGE_METHOD": "openrouter_pkce",
    "PUBLIC_ERROR_CLASSES": "managed_openrouter_broker_client",
    "PUBLIC_ERROR_CODES": "managed_openrouter_broker_client",
    "QQ_MANAGED_DELIVERY_ACK_TOKEN_SECRET": "managed_openrouter_release",
    "require_openrouter_execution_api_key": "openrouter_credentials",
    "resolve_openrouter_credentials": "openrouter_credentials",
    "RETRYABLE_ERROR_CLASS": "managed_openrouter_broker_client",
    "RETRYABLE_ERROR_CODE": "managed_openrouter_broker_client",
    "should_auto_show_founder_letter": "openrouter_handoff",
    "store_managed_entitlement_snapshot": "openrouter_handoff",
    "TalkTogetherPassStatus": "managed_openrouter_release",
    "UnavailableManagedOpenRouterReleaseClient": "managed_openrouter_release",
}

__all__ = [
    "best_effort_clear_managed_openrouter_user_identifier",
    "best_effort_store_managed_openrouter_user_identifier",
    "BINDING_MISMATCH_SUBCODES",
    "CALLBACK_TIMEOUT_SECONDS",
    "clear_temporary_managed_release_state",
    "DISCORD_MANAGED_DELIVERY_ACK_TOKEN_SECRET",
    "DiscordOAuthCallbackRunner",
    "DiscordOAuthListenerFactory",
    "format_managed_openrouter_diagnostics",
    "handle_managed_availability",
    "handle_managed_release_error",
    "HardwareFingerprintProvider",
    "HttpManagedOpenRouterBrokerClient",
    "is_effectively_exhausted",
    "load_managed_openrouter_user_identifier",
    "MANAGED_EFFECTIVE_EXHAUSTION_USD",
    "managed_openrouter_broker_client",
    "managed_openrouter_release",
    "MANAGED_OPENROUTER_TRIAL_BUDGET_USD",
    "ManagedOpenRouterChallengeSuccess",
    "ManagedOpenRouterDelegateFactory",
    "ManagedOpenRouterDiscordStartSuccess",
    "ManagedOpenRouterFingerprintSalt",
    "ManagedOpenRouterIssueSuccess",
    "ManagedOpenRouterLLMProvider",
    "ManagedOpenRouterPreflightStop",
    "ManagedOpenRouterReleaseBehavior",
    "ManagedOpenRouterReleaseClient",
    "ManagedOpenRouterReleaseDiagnostics",
    "ManagedOpenRouterReleaseError",
    "ManagedOpenRouterReleaseResult",
    "ManagedOpenRouterReleaseService",
    "ManagedOpenRouterStatusRefreshResult",
    "ManagedOpenRouterTrialStatusSuccess",
    "ManagedOpenRouterUserFacingError",
    "ManagedOpenRouterVerifySuccess",
    "mark_founder_letter_shown",
    "normalize_managed_openrouter_user_identifier",
    "OPENROUTER_AUTH_EXCHANGE_URL",
    "OPENROUTER_AUTH_URL",
    "OPENROUTER_BYOK_API_KEY_ENV",
    "OPENROUTER_BYOK_API_KEY_SECRET",
    "openrouter_credentials",
    "openrouter_handoff",
    "OPENROUTER_MANAGED_API_KEY_SECRET",
    "OPENROUTER_MANAGED_QQ_API_KEY_SECRET",
    "OPENROUTER_MANAGED_USER_ID_MAX_LENGTH",
    "OPENROUTER_MANAGED_USER_ID_SECRET",
    "OPENROUTER_MANAGED_USER_INSTALLATION_ID_SECRET",
    "openrouter_metadata",
    "openrouter_pkce",
    "OpenRouterCredentialResolution",
    "OpenRouterCredentialRuntimeConfig",
    "OpenRouterKeyMetadata",
    "OpenRouterManagedRecoveryAction",
    "OpenRouterManagedRecoveryResult",
    "OpenRouterPKCEClient",
    "OpenRouterPKCEExchangeResult",
    "OpenRouterPKCESession",
    "OpenRouterReleaseRuntimeConfig",
    "PKCE_CHALLENGE_METHOD",
    "PUBLIC_ERROR_CLASSES",
    "PUBLIC_ERROR_CODES",
    "QQ_MANAGED_DELIVERY_ACK_TOKEN_SECRET",
    "require_openrouter_execution_api_key",
    "resolve_openrouter_credentials",
    "RETRYABLE_ERROR_CLASS",
    "RETRYABLE_ERROR_CODE",
    "should_auto_show_founder_letter",
    "store_managed_entitlement_snapshot",
    "TalkTogetherPassStatus",
    "UnavailableManagedOpenRouterReleaseClient",
]


def __getattr__(name: str) -> object:
    if name in _SUBMODULES:
        return _import_module(f".{name}", __name__)
    source = _EXPORT_SOURCES.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(_import_module(f".{source}", __name__), name)
