from importlib import import_module as _import_module

_SUBMODULES = frozenset(
    {
        "overlay_application",
        "overlay_calibration",
        "overlay_calibration_application",
        "overlay_generation_start",
        "overlay_session_transition",
    }
)
_EXPORT_SOURCES = {
    "OVERLAY_FAILURE_REASONS": "overlay_application",
    "OVERLAY_SHUTDOWN_GRACE_S": "overlay_application",
    "OVERLAY_STARTUP_TIMEOUT_MS": "overlay_application",
    "OverlayApplicationOwner": "overlay_application",
    "OverlayApplicationSnapshot": "overlay_application",
    "OverlayApplicationState": "overlay_application",
    "OverlayAsyncEffect": "overlay_application",
    "OverlayBasicLogSink": "overlay_application",
    "OverlayBoundsControlSink": "overlay_application",
    "OverlayCalibrationApplicationOwner": "overlay_calibration_application",
    "OverlayCalibrationOwner": "overlay_calibration",
    "OverlayCalibrationProvider": "overlay_application",
    "OverlayConfigProvider": "overlay_application",
    "OverlayDesktopControlsFactory": "overlay_application",
    "OverlayDetailedLogSink": "overlay_application",
    "OverlayDiagnosticsProvider": "overlay_application",
    "OverlayEffect": "overlay_application",
    "OverlayFallbackNoticeSink": "overlay_application",
    "OverlayGenerationCalibrationSnapshot": "overlay_generation_start",
    "OverlayGenerationCloseStale": "overlay_generation_start",
    "OverlayGenerationConnectedHandler": "overlay_generation_start",
    "OverlayGenerationDesktopControls": "overlay_generation_start",
    "OverlayGenerationFailureHandler": "overlay_generation_start",
    "OverlayGenerationFailureLogger": "overlay_generation_start",
    "OverlayGenerationIsCurrent": "overlay_generation_start",
    "OverlayGenerationLocale": "overlay_generation_start",
    "OverlayGenerationLogDir": "overlay_generation_start",
    "OverlayGenerationLoggingMode": "overlay_generation_start",
    "OverlayGenerationMonitor": "overlay_generation_start",
    "OverlayGenerationProcessRunnerFactory": "overlay_generation_start",
    "OverlayGenerationRefresh": "overlay_generation_start",
    "OverlayGenerationRendererEvents": "overlay_generation_start",
    "OverlayGenerationReplaceSink": "overlay_generation_start",
    "OverlayGenerationRequestFactory": "overlay_generation_start",
    "OverlayGenerationRetryOwnership": "overlay_generation_start",
    "OverlayGenerationRuntimeLogger": "overlay_generation_start",
    "OverlayGenerationSetDiagnostics": "overlay_generation_start",
    "OverlayGenerationSetInteractionMode": "overlay_generation_start",
    "OverlayGenerationSetTarget": "overlay_generation_start",
    "OverlayGenerationStartDiagnostic": "overlay_generation_start",
    "OverlayGenerationStartDiagnosticSink": "overlay_generation_start",
    "OverlayGenerationStartEffects": "overlay_generation_start",
    "OverlayGenerationStartOwner": "overlay_generation_start",
    "OverlayGenerationStartRequest": "overlay_generation_start",
    "OverlayGenerationStartStatus": "overlay_generation_start",
    "OverlayGenerationTrackBounds": "overlay_generation_start",
    "OverlayIntentSink": "overlay_application",
    "OverlayInteractionModeSink": "overlay_application",
    "OverlayOutputProvider": "overlay_application",
    "OverlayPeerSnapshotProvider": "overlay_application",
    "OverlayPresentationSink": "overlay_application",
    "OverlayRendererEventConsumer": "overlay_application",
    "OverlaySessionCompletionHandler": "overlay_session_transition",
    "OverlaySessionResourceProbe": "overlay_session_transition",
    "OverlaySessionRuntimeFactory": "overlay_session_transition",
    "OverlaySessionShutdownExecution": "overlay_session_transition",
    "OverlaySessionShutdownExecutionFactory": "overlay_session_transition",
    "OverlaySessionShutdownStatus": "overlay_session_transition",
    "OverlaySessionStartExecution": "overlay_session_transition",
    "OverlaySessionStartExecutionFactory": "overlay_session_transition",
    "OverlaySessionStartingHandler": "overlay_session_transition",
    "OverlaySessionStartOperation": "overlay_session_transition",
    "OverlaySessionStartStatus": "overlay_session_transition",
    "OverlaySessionStateHandler": "overlay_session_transition",
    "OverlaySessionTargetFactory": "overlay_session_transition",
    "OverlaySessionTeardown": "overlay_session_transition",
    "OverlaySessionTransitionDiagnostic": "overlay_session_transition",
    "OverlaySessionTransitionDiagnosticSink": "overlay_session_transition",
    "OverlaySessionTransitionOwner": "overlay_session_transition",
    "OverlayStateProvider": "overlay_application",
    "OverlayStateSink": "overlay_application",
    "OverlayValueProvider": "overlay_application",
}

__all__ = [
    "overlay_application",
    "overlay_calibration",
    "overlay_calibration_application",
    "OVERLAY_FAILURE_REASONS",
    "overlay_generation_start",
    "overlay_session_transition",
    "OVERLAY_SHUTDOWN_GRACE_S",
    "OVERLAY_STARTUP_TIMEOUT_MS",
    "OverlayApplicationOwner",
    "OverlayApplicationSnapshot",
    "OverlayApplicationState",
    "OverlayAsyncEffect",
    "OverlayBasicLogSink",
    "OverlayBoundsControlSink",
    "OverlayCalibrationApplicationOwner",
    "OverlayCalibrationOwner",
    "OverlayCalibrationProvider",
    "OverlayConfigProvider",
    "OverlayDesktopControlsFactory",
    "OverlayDetailedLogSink",
    "OverlayDiagnosticsProvider",
    "OverlayEffect",
    "OverlayFallbackNoticeSink",
    "OverlayGenerationCalibrationSnapshot",
    "OverlayGenerationCloseStale",
    "OverlayGenerationConnectedHandler",
    "OverlayGenerationDesktopControls",
    "OverlayGenerationFailureHandler",
    "OverlayGenerationFailureLogger",
    "OverlayGenerationIsCurrent",
    "OverlayGenerationLocale",
    "OverlayGenerationLogDir",
    "OverlayGenerationLoggingMode",
    "OverlayGenerationMonitor",
    "OverlayGenerationProcessRunnerFactory",
    "OverlayGenerationRefresh",
    "OverlayGenerationRendererEvents",
    "OverlayGenerationReplaceSink",
    "OverlayGenerationRequestFactory",
    "OverlayGenerationRetryOwnership",
    "OverlayGenerationRuntimeLogger",
    "OverlayGenerationSetDiagnostics",
    "OverlayGenerationSetInteractionMode",
    "OverlayGenerationSetTarget",
    "OverlayGenerationStartDiagnostic",
    "OverlayGenerationStartDiagnosticSink",
    "OverlayGenerationStartEffects",
    "OverlayGenerationStartOwner",
    "OverlayGenerationStartRequest",
    "OverlayGenerationStartStatus",
    "OverlayGenerationTrackBounds",
    "OverlayIntentSink",
    "OverlayInteractionModeSink",
    "OverlayOutputProvider",
    "OverlayPeerSnapshotProvider",
    "OverlayPresentationSink",
    "OverlayRendererEventConsumer",
    "OverlaySessionCompletionHandler",
    "OverlaySessionResourceProbe",
    "OverlaySessionRuntimeFactory",
    "OverlaySessionShutdownExecution",
    "OverlaySessionShutdownExecutionFactory",
    "OverlaySessionShutdownStatus",
    "OverlaySessionStartExecution",
    "OverlaySessionStartExecutionFactory",
    "OverlaySessionStartingHandler",
    "OverlaySessionStartOperation",
    "OverlaySessionStartStatus",
    "OverlaySessionStateHandler",
    "OverlaySessionTargetFactory",
    "OverlaySessionTeardown",
    "OverlaySessionTransitionDiagnostic",
    "OverlaySessionTransitionDiagnosticSink",
    "OverlaySessionTransitionOwner",
    "OverlayStateProvider",
    "OverlayStateSink",
    "OverlayValueProvider",
]


def __getattr__(name: str) -> object:
    if name in _SUBMODULES:
        return _import_module(f".{name}", __name__)
    source = _EXPORT_SOURCES.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(_import_module(f".{source}", __name__), name)
