from importlib import import_module as _import_module

_SUBMODULES = frozenset(
    {
        "settings_application",
        "settings_mutation",
        "settings_mutation_legacy",
        "settings_projection",
        "settings_runtime_effects",
        "settings_transaction_result",
    }
)
_EXPORT_SOURCES = {
    "build_overlay_osc_output_settings_path_patch": "settings_mutation_legacy",
    "build_stt_language_audio_settings_path_patch": "settings_mutation_legacy",
    "build_translation_provider_settings_path_patch": "settings_mutation_legacy",
    "build_ui_prompt_clipboard_state_settings_path_patch": "settings_mutation_legacy",
    "ORDER21_TRANSLATION_PROVIDER_SETTINGS_PATHS": "settings_mutation_legacy",
    "ORDER22_STT_LANGUAGE_AUDIO_SETTINGS_PATHS": "settings_mutation_legacy",
    "ORDER23_OVERLAY_OSC_OUTPUT_SETTINGS_PATHS": "settings_mutation_legacy",
    "ORDER24_UI_PROMPT_CLIPBOARD_STATE_SETTINGS_PATHS": "settings_mutation_legacy",
    "OverlayOscOutputSettingsMutation": "settings_mutation",
    "RuntimeApplyResultPublisher": "settings_mutation",
    "SETTINGS_MUTATION_SURFACE_OVERLAY_OSC_OUTPUT": "settings_mutation",
    "SETTINGS_MUTATION_SURFACE_STT_LANGUAGE_AUDIO": "settings_mutation",
    "SETTINGS_MUTATION_SURFACE_TRANSLATION_PROVIDER": "settings_mutation",
    "SETTINGS_MUTATION_SURFACE_UI_PROMPT_CLIPBOARD_STATE": "settings_mutation",
    "settings_path_mutation_validator_for_command": "settings_mutation_legacy",
    "settings_path_patch_from_command": "settings_mutation_legacy",
    "settings_path_snapshot_for_overlay_osc_output": "settings_mutation_legacy",
    "settings_path_snapshot_for_stt_language_audio": "settings_mutation_legacy",
    "settings_path_snapshot_for_ui_prompt_clipboard_state": "settings_mutation_legacy",
    "SettingsApplicationOwner": "settings_application",
    "SettingsAsyncEffect": "settings_application",
    "SettingsFailureSink": "settings_application",
    "SettingsFallbackLogSink": "settings_application",
    "SettingsFallbackSink": "settings_application",
    "SettingsMutationCommand": "settings_mutation",
    "SettingsMutationRequest": "settings_mutation",
    "SettingsMutationService": "settings_mutation",
    "SettingsMutationServiceProvider": "settings_application",
    "SettingsMutationValidationResult": "settings_mutation",
    "SettingsMutationValidator": "settings_mutation",
    "SettingsPathMutationValidator": "settings_mutation_legacy",
    "SettingsPathPatch": "settings_mutation_legacy",
    "SettingsPredicate": "settings_application",
    "SettingsProjectionOwner": "settings_projection",
    "SettingsRuntimeEffectsAdapter": "settings_runtime_effects",
    "SettingsRuntimeEffectsState": "settings_runtime_effects",
    "SettingsSnapshotPublisher": "settings_mutation",
    "SettingsTransactionResultOwner": "settings_transaction_result",
    "SettingsViewSettingsChange": "settings_projection",
    "StrictSettingsSaveFailed": "settings_application",
    "SttLanguageAudioSettingsMutation": "settings_mutation",
    "TranslationProviderSettingsMutation": "settings_mutation",
    "UiPromptClipboardStateSettingsMutation": "settings_mutation",
}

__all__ = [
    "build_overlay_osc_output_settings_path_patch",
    "build_stt_language_audio_settings_path_patch",
    "build_translation_provider_settings_path_patch",
    "build_ui_prompt_clipboard_state_settings_path_patch",
    "ORDER21_TRANSLATION_PROVIDER_SETTINGS_PATHS",
    "ORDER22_STT_LANGUAGE_AUDIO_SETTINGS_PATHS",
    "ORDER23_OVERLAY_OSC_OUTPUT_SETTINGS_PATHS",
    "ORDER24_UI_PROMPT_CLIPBOARD_STATE_SETTINGS_PATHS",
    "OverlayOscOutputSettingsMutation",
    "RuntimeApplyResultPublisher",
    "settings_application",
    "settings_mutation",
    "settings_mutation_legacy",
    "SETTINGS_MUTATION_SURFACE_OVERLAY_OSC_OUTPUT",
    "SETTINGS_MUTATION_SURFACE_STT_LANGUAGE_AUDIO",
    "SETTINGS_MUTATION_SURFACE_TRANSLATION_PROVIDER",
    "SETTINGS_MUTATION_SURFACE_UI_PROMPT_CLIPBOARD_STATE",
    "settings_path_mutation_validator_for_command",
    "settings_path_patch_from_command",
    "settings_path_snapshot_for_overlay_osc_output",
    "settings_path_snapshot_for_stt_language_audio",
    "settings_path_snapshot_for_ui_prompt_clipboard_state",
    "settings_projection",
    "settings_runtime_effects",
    "settings_transaction_result",
    "SettingsApplicationOwner",
    "SettingsAsyncEffect",
    "SettingsFailureSink",
    "SettingsFallbackLogSink",
    "SettingsFallbackSink",
    "SettingsMutationCommand",
    "SettingsMutationRequest",
    "SettingsMutationService",
    "SettingsMutationServiceProvider",
    "SettingsMutationValidationResult",
    "SettingsMutationValidator",
    "SettingsPathMutationValidator",
    "SettingsPathPatch",
    "SettingsPredicate",
    "SettingsProjectionOwner",
    "SettingsRuntimeEffectsAdapter",
    "SettingsRuntimeEffectsState",
    "SettingsSnapshotPublisher",
    "SettingsTransactionResultOwner",
    "SettingsViewSettingsChange",
    "StrictSettingsSaveFailed",
    "SttLanguageAudioSettingsMutation",
    "TranslationProviderSettingsMutation",
    "UiPromptClipboardStateSettingsMutation",
]


def __getattr__(name: str) -> object:
    if name in _SUBMODULES:
        return _import_module(f".{name}", __name__)
    source = _EXPORT_SOURCES.get(name)
    if source is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    return getattr(_import_module(f".{source}", __name__), name)
